#pragma once
#include <glad\glad.h>
#include "./MutilThreadBase/RefCount.h"
#include "./UI/Window.h"
#include "./UI/GLFW_WindowShareData.h"
#include "./UI/GLFW_Window.h"
#include "./Context/IRenderTarget.h"
#include "./Context/Context.h"
#include "./Context/GL_Context.h"
#include "./Context/GL_ContextShareData.h"
#include "./Context/D3D11_Context.h"
#include "./Context/VertexFactory.h"
#include "./Runtime/runtime.h"
#pragma comment(lib,"FCT.lib")
